workflows:
    version: 2
    build:
        jobs:
            - build_node_12
            - build_node_14
            - build_node_16

version: 2
jobs:
    base: &base
        working_directory: ~/workspace
        docker:
            - image: cimg/node:12.18.2
        steps:
            - checkout
            - restore_cache:
                key: add-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}
            - run: git submodule update --init
            - run:
                name: Install dependencies
                command: npm i --registry https://registry.npmjs.org
            - run:
                name: Build samples
                command: ./build-samples.sh
            - save_cache:
                key: add-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum "npm-shrinkwrap.json" }}
                paths:
                    - "node_modules"

    build_node_12:
        <<: *base
        docker:
        - image: cimg/node:12.18.2

    build_node_14:
        <<: *base
        docker:
        - image: cimg/node:14.17.0

    build_node_16:
        <<: *base
        docker:
        - image: cimg/node:16.1.0
